[package]
name = "scion"
version = "0.1.0"
authors = ["grzi <jeremy.thulliez@gmail.com>"]
edition = "2018"

[features]
parallel = ["legion/parallel"]

[dependencies]
legion = { git = "https://github.com/grzi/legion", branch = "feat/uuid_as_optional", default-features = false, features = ["codegen"]}

# window & rendering
miniquad = "0.3.0-alpha.26"

# serialization
serde = { version = "1.0.124", features = ["derive"] }
toml = "0.5.8"

# logging
log = { version = "0.4.14", features = ["serde"] }
fern = { version = "0.6.0", features = ["colored"] }